"""Generate one dummy certificate from workflow inputs, optionally email it via Resend.

This script intentionally does not read or update Supabase. It is only for
testing the certificate template and optional email delivery.
"""

import argparse
import base64
import os
import sys
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config import CERT_VERIFY_BASE_URL, FROM_EMAIL, FEST_NAME
from generate import generate_certificate_to_file, make_cert_id


def send_email(email, name, event_name, cert_id, filepath):
    api_key = os.environ.get("RESEND_API_KEY", "").strip()
    if not api_key:
        raise RuntimeError("RESEND_API_KEY is required when --send-email is enabled")

    import resend

    resend.api_key = api_key
    verify_url = f"{CERT_VERIFY_BASE_URL}/verify/{cert_id}/"

    with open(filepath, "rb") as f:
        content = base64.b64encode(f.read()).decode("utf-8")

    response = resend.Emails.send({
        "from": FROM_EMAIL,
        "to": [email],
        "subject": f"Certificate of Participation - {event_name}",
        "html": f"""<!DOCTYPE html>
<html>
<body style="font-family:Arial,sans-serif;line-height:1.6;color:#222;">
  <h2>Your Certificate of Participation</h2>
  <p>Hi <strong>{name}</strong>,</p>
  <p>Your certificate for <strong>{event_name}</strong> is attached.</p>
  <p><strong>Certificate ID:</strong> {cert_id}</p>
  <p>This is a dummy/test certificate generated by the Astra Certificate workflow.</p>
  <p><a href="{verify_url}">Verify certificate</a></p>
</body>
</html>""",
        "attachments": [{
            "filename": os.path.basename(filepath),
            "content": content,
        }],
    })

    print(f"Email sent to {email}. Resend ID: {response.get('id', 'unknown')}")


def main():
    parser = argparse.ArgumentParser(description="Generate a dummy Astra certificate")
    parser.add_argument("--name", required=True)
    parser.add_argument("--event-name", required=True)
    parser.add_argument("--college", required=True)
    parser.add_argument("--email", default="")
    parser.add_argument("--send-email", action="store_true")
    args = parser.parse_args()

    if args.send_email and not args.email.strip():
        parser.error("--email is required when --send-email is enabled")

    participant = {
        "name": args.name.strip(),
        "email": args.email.strip(),
        "college": args.college.strip(),
    }

    event_info = {
        "title": args.event_name.strip(),
        "fest_name": FEST_NAME,
        "date_str": os.environ.get(
            "EVENT_DATE_STR",
            datetime.now().strftime("%-d %B %Y").upper(),
        ),
    }

    cert_id = make_cert_id(datetime.now().year, 9999)
    output_dir = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "dummy-output",
    )

    filepath = generate_certificate_to_file(
        participant,
        event_info,
        cert_id,
        output_dir=output_dir,
    )

    print(f"Generated certificate: {filepath}")
    print(f"Name: {participant['name']}")
    print(f"Event: {event_info['title']}")
    print(f"College: {participant['college']}")
    print(f"Certificate ID: {cert_id}")

    if args.send_email:
        send_email(
            participant["email"],
            participant["name"],
            event_info["title"],
            cert_id,
            filepath,
        )
    else:
        print("Email sending disabled.")


if __name__ == "__main__":
    main()
